name: 'Reload pythonanywhere webapp'
description: 'GitHub action to reload a webapp on pythonanywhere'
inputs:
  host:
    description: 'Pythonanywhere host (EU/US), can be either eu.pythonanywhere.com or www.pythonanywhere.com (default)'
    required: true
    default: 'www.pythonanyhwere.com'
  username:
    description: 'Username for pythonanywhere'
    required: true
  api-token: 
    description: 'API token for pythonanywhere'
    required: true
  domain-name:
    description: 'Domain name of the webapp to reload'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
